// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtrCdSsInIBUh9TQ1r1CdSJLtDj7pBbI',
    appId: '1:171282885839:web:d7d03b08505c68b9e8dbba',
    messagingSenderId: '171282885839',
    projectId: 'exchange-rates-app-5dfeb',
    authDomain: 'exchange-rates-app-5dfeb.firebaseapp.com',
    storageBucket: 'exchange-rates-app-5dfeb.appspot.com',
    measurementId: 'G-E9NMN02BWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOh63D2juutLAd7P1BEQN6xSsxnCxujWw',
    appId: '1:171282885839:android:8beed6895d0bcecde8dbba',
    messagingSenderId: '171282885839',
    projectId: 'exchange-rates-app-5dfeb',
    storageBucket: 'exchange-rates-app-5dfeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEoNcYPoqAi2k6jbjvmtKwx2NMYRulibs',
    appId: '1:171282885839:ios:e12dc5ec7055755be8dbba',
    messagingSenderId: '171282885839',
    projectId: 'exchange-rates-app-5dfeb',
    storageBucket: 'exchange-rates-app-5dfeb.appspot.com',
    iosBundleId: 'com.example.exchangeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEoNcYPoqAi2k6jbjvmtKwx2NMYRulibs',
    appId: '1:171282885839:ios:e12dc5ec7055755be8dbba',
    messagingSenderId: '171282885839',
    projectId: 'exchange-rates-app-5dfeb',
    storageBucket: 'exchange-rates-app-5dfeb.appspot.com',
    iosBundleId: 'com.example.exchangeApp',
  );
}
